import { Translations } from './types';

export const TRANSLATIONS: Translations = {
    ru: {
        nav_about: "О проекте",
        nav_eligibility: "Кто может подать",
        nav_timeline: "Сроки",
        nav_contacts: "Контакты",
        btn_apply: "Подать заявку",
        hero_title: "Конкурс малых грантов для гражданского общества",
        hero_subtitle: "Проект «Расширение возможностей гражданского общества для инклюзивного развития сообществ в Узбекистане»",
        hero_max_amount: "Макс. сумма гранта",
        hero_deadline_date: "16 Янв 2026",
        hero_deadline_label: "Дедлайн подачи",
        section_goal_title: "Цель конкурса",
        section_goal_desc: "Поддержка инициатив ННО/ОГО, направленных на развитие регионов через:",
        goal_1_title: "Участие",
        goal_1_desc: "Укрепление участия молодёжи и женщин.",
        goal_2_title: "Экология",
        goal_2_desc: "Обеспечение экологической устойчивости.",
        goal_3_title: "Медиа",
        goal_3_desc: "Развитие современной медиаграмотности.",
        section_eligibility_title: "Условия участия",
        eligibility_who_title: "Кто может подать заявку?",
        eligibility_who_1: "Зарегистрированные ННО/ОГО Узбекистана.",
        eligibility_who_2: "Допустимы консорциумы.",
        eligibility_who_3: "Возможны совместные заявки (Ведущий заявитель + со-заявители).",
        eligibility_geo_title: "Географический приоритет",
        geo_karakalpakstan: "Республика Каракалпакстан",
        geo_kashkadarya: "Кашкадарьинская область",
        geo_fergana: "Ферганская область",
        section_timeline_title: "График конкурса",
        timeline_1_date: "10 & 23 Декабря 2025",
        timeline_1_title: "Информационные сессии",
        timeline_1_desc: "Разъяснение условий конкурса для заявителей.",
        timeline_2_date: "30 Декабря 2025",
        timeline_2_title: "Срок запросов на разъяснения",
        timeline_3_date: "16 Января 2026",
        timeline_3_title: "Дедлайн подачи заявок",
        timeline_3_desc: "Заявки принимаются до 23:59 по Ташкенту.",
        timeline_4_date: "Февраль 2026",
        timeline_4_title: "Объявление победителей",
        timeline_4_desc: "Административная проверка и качественная оценка.",
        sidebar_apply_title: "Подать заявку",
        sidebar_apply_desc: "Заявки принимаются в электронном виде (одним архивом) по электронной почте.",
        sidebar_sum_label: "Сумма гранта",
        sidebar_sum_value: "до € 7,000",
        sidebar_duration_label: "Срок реализации",
        sidebar_duration_value: "4 – 6 месяцев",
        btn_send_apply: "Отправить заявку",
        sidebar_subject_hint: "Тема письма должна быть:",
        sidebar_docs_title: "Документы",
        sidebar_docs_guide: "Руководство для заявителей",
        sidebar_docs_open: "Открыть в Google Docs",
        sidebar_contact_title: "Контакты",
        footer_eu: "Проект реализуется при софинансировании Европейского Союза."
    },
    uz: {
        nav_about: "Loyiha haqida",
        nav_eligibility: "Kim topshirishi mumkin",
        nav_timeline: "Muddatlar",
        nav_contacts: "Aloqa",
        btn_apply: "Ariza topshirish",
        hero_title: "Fuqarolik jamiyati uchun kichik grantlar tanlovi",
        hero_subtitle: "«O‘zbekistonda hamjamiyatlarni inklyuziv rivojlantirish uchun fuqarolik jamiyati imkoniyatlarini kengaytirish» loyihasi",
        hero_max_amount: "Maks. grant miqdori",
        hero_deadline_date: "16 Yan 2026",
        hero_deadline_label: "Ariza topshirish muddati",
        section_goal_title: "Tanlov maqsadi",
        section_goal_desc: "Hududlarni quyidagilar orqali rivojlantirishga qaratilgan NNT/FJT tashabbuslarini qo‘llab-quvvatlash:",
        goal_1_title: "Ishtirok",
        goal_1_desc: "Yoshlar va xotin-qizlar ishtirokini kuchaytirish.",
        goal_2_title: "Ekologiya",
        goal_2_desc: "Ekologik barqarorlikni ta'minlash.",
        goal_3_title: "Media",
        goal_3_desc: "Zamonaviy media savodxonlikni rivojlantirish.",
        section_eligibility_title: "Ishtirok etish shartlari",
        eligibility_who_title: "Kim ariza topshirishi mumkin?",
        eligibility_who_1: "O‘zbekistonda ro‘yxatdan o‘tgan NNT/FJT.",
        eligibility_who_2: "Konsorsiumlar ruxsat etiladi.",
        eligibility_who_3: "Qo‘shma arizalar mumkin (Asosiy arizachi + sheriklar).",
        eligibility_geo_title: "Geografik ustuvorlik",
        geo_karakalpakstan: "Qoraqalpog‘iston Respublikasi",
        geo_kashkadarya: "Qashqadaryo viloyati",
        geo_fergana: "Farg‘ona viloyati",
        section_timeline_title: "Tanlov jadvali",
        timeline_1_date: "10 & 23 Dekabr 2025",
        timeline_1_title: "Axborot sessiyalari",
        timeline_1_desc: "Arizachilar uchun tanlov shartlarini tushuntirish.",
        timeline_2_date: "30 Dekabr 2025",
        timeline_2_title: "Tushuntirish so‘rovlari uchun muddat",
        timeline_3_date: "16 Yanvar 2026",
        timeline_3_title: "Ariza topshirish muddati",
        timeline_3_desc: "Arizalar Toshkent vaqti bilan 23:59 gacha qabul qilinadi.",
        timeline_4_date: "Fevral 2026",
        timeline_4_title: "G‘oliblarni e'lon qilish",
        timeline_4_desc: "Ma'muriy tekshiruv va sifat baholash.",
        sidebar_apply_title: "Ariza topshirish",
        sidebar_apply_desc: "Arizalar elektron shaklda (bitta arxivda) elektron pochta orqali qabul qilinadi.",
        sidebar_sum_label: "Grant miqdori",
        sidebar_sum_value: "€ 7,000 gacha",
        sidebar_duration_label: "Amalga oshirish muddati",
        sidebar_duration_value: "4 – 6 oy",
        btn_send_apply: "Ariza yuborish",
        sidebar_subject_hint: "Xat mavzusi quyidagicha bo‘lishi kerak:",
        sidebar_docs_title: "Hujjatlar",
        sidebar_docs_guide: "Ariza beruvchilar uchun qo‘llanma",
        sidebar_docs_open: "Google Docs-da ochish",
        sidebar_contact_title: "Aloqa",
        footer_eu: "Loyiha Yevropa Ittifoqi tomonidan hamkorlikda moliyalashtirilmoqda."
    },
    en: {
        nav_about: "About",
        nav_eligibility: "Eligibility",
        nav_timeline: "Timeline",
        nav_contacts: "Contacts",
        btn_apply: "Apply Now",
        hero_title: "Small Grants Competition for Civil Society",
        hero_subtitle: "Project 'Empowering Civil Society for Inclusive Community Development in Uzbekistan'",
        hero_max_amount: "Max. Grant Amount",
        hero_deadline_date: "Jan 16, 2026",
        hero_deadline_label: "Submission Deadline",
        section_goal_title: "Competition Goal",
        section_goal_desc: "Supporting NGO/CSO initiatives aimed at regional development through:",
        goal_1_title: "Participation",
        goal_1_desc: "Strengthening youth and women participation.",
        goal_2_title: "Ecology",
        goal_2_desc: "Ensuring environmental sustainability.",
        goal_3_title: "Media",
        goal_3_desc: "Developing modern media literacy.",
        section_eligibility_title: "Eligibility Criteria",
        eligibility_who_title: "Who can apply?",
        eligibility_who_1: "Registered NGOs/CSOs in Uzbekistan.",
        eligibility_who_2: "Consortiums are allowed.",
        eligibility_who_3: "Joint applications possible (Lead applicant + co-applicants).",
        eligibility_geo_title: "Geographic Priority",
        geo_karakalpakstan: "Republic of Karakalpakstan",
        geo_kashkadarya: "Kashkadarya Region",
        geo_fergana: "Fergana Region",
        section_timeline_title: "Competition Timeline",
        timeline_1_date: "Dec 10 & 23, 2025",
        timeline_1_title: "Information Sessions",
        timeline_1_desc: "Clarification of competition terms for applicants.",
        timeline_2_date: "Dec 30, 2025",
        timeline_2_title: "Deadline for Clarification Requests",
        timeline_3_date: "Jan 16, 2026",
        timeline_3_title: "Submission Deadline",
        timeline_3_desc: "Applications accepted until 23:59 Tashkent time.",
        timeline_4_date: "February 2026",
        timeline_4_title: "Winners Announcement",
        timeline_4_desc: "Administrative check and qualitative assessment.",
        sidebar_apply_title: "Apply Now",
        sidebar_apply_desc: "Applications accepted electronically (one archive) via email.",
        sidebar_sum_label: "Grant Amount",
        sidebar_sum_value: "up to € 7,000",
        sidebar_duration_label: "Implementation Period",
        sidebar_duration_value: "4 – 6 months",
        btn_send_apply: "Send Application",
        sidebar_subject_hint: "Email subject must be:",
        sidebar_docs_title: "Documents",
        sidebar_docs_guide: "Guidelines for Applicants",
        sidebar_docs_open: "Open in Google Docs",
        sidebar_contact_title: "Contacts",
        footer_eu: "Project co-funded by the European Union."
    }
};